plugins {
    id 'org.springframework.boot' version '3.2.5'
    id 'io.spring.dependency-management' version '1.1.4'
}

group = 'com.kenzie.unit.four'
version = '0.0.1-SNAPSHOT'

dependencies {
    implementation project(":ServiceLambdaModel")
    implementation project(":ServiceLambdaJavaClient")
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    implementation group: 'org.springframework.boot', name: 'spring-boot-starter-actuator'

    implementation 'com.google.guava:guava:31.1-jre'
    implementation group: 'com.github.ben-manes.caffeine', name: 'caffeine', version: '2.9.3'
    implementation group: 'org.springframework.boot', name: 'spring-boot-starter-cache'

    implementation group: 'io.micrometer', name: 'micrometer-core', version: '1.8.3'
    implementation group: 'io.micrometer', name: 'micrometer-registry-prometheus', version: '1.8.3'
    implementation group: 'io.micrometer', name: 'micrometer-registry-cloudwatch2', version: '1.8.3'

    implementation 'io.awspring.cloud:spring-cloud-aws-starter:3.1.1'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.3.0'
    
    implementation 'software.amazon.awssdk:dynamodb-enhanced'
    implementation 'software.amazon.awssdk:dynamodb'

    testImplementation group: 'org.testcontainers', name: 'testcontainers', version: '1.16.3'
    testImplementation 'net.andreinc:mockneat:0.4.8'
}
dependencyManagement {
    imports {
        mavenBom 'software.amazon.awssdk:bom:2.25.23'
    }
}

processResources {
    expand(project.properties)
}

task buildZip(type: Zip) {
    from compileJava
    from processResources
    into('lib') {
        from configurations.runtimeClasspath
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

repositories {
    maven {
        url 'https://repo.maven.apache.org/maven2'
        name 'Maven Central'
    }
}

task copyFrontend(type: Copy) {
    dependsOn(":Frontend:yarn_build")

    from("../Frontend/dist")
    into("build/resources/main/static")
}

if (project.hasProperty('includeFrontend')) {
    compileJava.dependsOn(copyFrontend)
}

task bootRunDev {
    bootRun.configure {
        systemProperty "spring.profiles.active", 'local'
    }
}

bootRunDev.finalizedBy bootRun
