Resources:
  FundraisingEventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "campaignId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: "CampaignIdIndex"
          KeySchema:
            - AttributeName: "campaignId"
              KeyType: "HASH"
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      TableName: "FundraisingEvents"

# Deploy:
#   aws cloudformation create-stack \
#     --stack-name fundraising-events \
#     --template-body file://FundraisingEventsTable.yml \
#     --capabilities CAPABILITY_IAM
